name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: install modules
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: build production project
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod

      - name: linting typescript
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:ts

      - name: linting css
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:scss

      - name: unit testing
        uses: borales/actions-yarn@v4
        with:
          cmd: test:unit
